# Generated by Django 3.1.3 on 2021-05-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideal_api', '0003_auto_20210521_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='mission',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='philosophy',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='professionalism',
        ),
        migrations.RemoveField(
            model_name='about',
            name='vision',
        ),
    ]
