# Generated by Django 3.1.3 on 2021-05-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideal_api', '0004_auto_20210521_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
